//
//  MasterViewController.swift
//  NumbersApplication
//
//  Created by Kamil Buczel on 21.01.2018.
//  Copyright (c) 2018 Kamajabu. All rights reserved.
//
//  This file was generated by the MVP Templates created by Kamil Buczel//

import Foundation
import UIKit

class MasterViewController: UITableViewController, MasterView, UISplitViewControllerDelegate  {
    var configurator = MasterConfiguratorImplementation()
    var presenter: MasterPresenter!

    override func viewDidLoad() {
        super.viewDidLoad()
        configurator.configure(masterViewController: self)
        splitViewController?.delegate = self

        presenter.viewDidLoad()
    }

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)

        let orientationAfterTransition = UIDevice.current.orientation
        let isLandscape = orientationAfterTransition.isLandscape

        if(presenter.selectedIndexPath != nil && isLandscape) {
            self.tableView.selectRow(at: presenter.selectedIndexPath,
                                     animated: true,
                                     scrollPosition:UITableViewScrollPosition.middle)

            presenter.orientationJustChanged = false
        }
    }

    func displayErrorMessage(details: String) {
        let alert = UIAlertController(title: "Error",
                                      message: details,
                                      preferredStyle: .alert)

        alert.addAction(UIAlertAction(title: "No", style: .cancel, handler: nil))

        self.present(alert, animated: true)
    }

    func reloadCollection() {
        //TODO
        self.tableView.reloadData()

        let initialOrientation = UIApplication.shared.statusBarOrientation
        if (initialOrientation.isLandscape) {

            let initialIndexPath = IndexPath(row: 0, section: 0)
            self.tableView.selectRow(at: initialIndexPath, animated: true,
                                     scrollPosition:UITableViewScrollPosition.none)

            self.performSegue(withIdentifier: MasterConsts.detailSegue, sender: initialIndexPath)
        }

    }

    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return presenter.masterDataArray.count
    }

    override func tableView(_ tableView: UITableView,
                            cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(
            withIdentifier: MasterConsts.cellIdentifier, for: indexPath) as! MasterTableViewCell

        presenter.configureCell(cell: cell, row: indexPath.row)

        return cell
    }

    override func tableView(_ tableView: UITableView,
                            heightForRowAt indexPath: IndexPath) -> CGFloat {
        return CGFloat(MasterConsts.cellHeight)
    }

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if segue.identifier == MasterConsts.detailSegue {
            let navigation = segue.destination as! UINavigationController
            let controller = navigation.topViewController as! DetailsViewController
            let selectedIndex = tableView.indexPathForSelectedRow
            presenter.prepareDestinationController(controller: controller,
                                                   selectedIndex: selectedIndex!)
        }
    }
}

