//
//  MasterViewController.swift
//  NumbersApplication
//
//  Created by Kamil Buczel on 21.01.2018.
//  Copyright (c) 2018 Kamajabu. All rights reserved.
//
//  This file was generated by the MVP Templates created by Kamil Buczel//

import Foundation
import UIKit

class MasterViewController: UITableViewController, MasterView, ViewWithAlert,
UISplitViewControllerDelegate  {
    var configurator = MasterConfiguratorImplementation()
    var presenter: MasterPresenter!

    override func viewDidLoad() {
        super.viewDidLoad()
        configurator.configure(masterViewController: self)
        splitViewController?.delegate = self
        splitViewController?.presentsWithGesture = false

        presenter.viewDidLoad()
    }

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)

        if(checkIfDeviceIsLandscape()) {
            presenter.selectCurrentlyViewedDetailOnList()
        }
    }

    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()

        if(checkIfDeviceIsLandscape()) {
            presenter.checkIfInitialItemNeedsToBeSet()
        }
    }

    func reloadCollection() {
        self.tableView.reloadData()

        if(checkIfInitialOrientationIsLandscape()) {
            presenter.checkIfInitialItemNeedsToBeSet()
        }
    }

    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return presenter.masterDataArray.count
    }

    override func tableView(_ tableView: UITableView,
                            cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(
            withIdentifier: MasterConsts.cellIdentifier, for: indexPath) as! MasterTableViewCell

        presenter.configureCell(cell: cell, row: indexPath.row)

        return cell
    }

    override func tableView(_ tableView: UITableView,
                            heightForRowAt indexPath: IndexPath) -> CGFloat {
        return CGFloat(MasterConsts.cellHeight)
    }

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if segue.identifier == MasterConsts.detailSegue {
            let navigation = segue.destination as! UINavigationController
            let controller = navigation.topViewController as! DetailsViewController
            let selectedIndex = tableView.indexPathForSelectedRow
            presenter.prepareDestinationController(controller: controller,
                                                   selectedIndex: selectedIndex!)
        }
    }

    func checkIfDeviceIsLandscape() -> Bool {
        let orientationAfterTransition = UIDevice.current.orientation
        return orientationAfterTransition.isLandscape
    }

    func checkIfInitialOrientationIsLandscape() -> Bool {
        let initialOrientation = UIApplication.shared.statusBarOrientation
        return initialOrientation.isLandscape
    }

    func selectMasterRow(_ indexPath: IndexPath) {
        self.tableView.selectRow(at: indexPath,
                                 animated: true,
                                 scrollPosition: .middle)
        self.performSegue(withIdentifier: MasterConsts.detailSegue, sender: indexPath)

    }

    func displayErrorMessage(details: String) {
        AlertModule().displayErrorMessage(details: details,
                                          viewInterface: self,
                                          parentView: self)
    }

    func retryAction() {
        presenter.retryFetch()
    }

    func splitViewController(_ splitViewController: UISplitViewController,
                             collapseSecondary secondaryViewController: UIViewController,
                             onto primaryViewController: UIViewController) -> Bool {
        return true
    }
}

