//
//  DetailsView.swift
//  NumbersApplication
//
//  Created by Kamil Buczel on 21.01.2018.
//  Copyright (c) 2018 Kamajabu. All rights reserved.
//
//  This file was generated by the MVP Templates created by Kamil Buczel//

import UIKit

protocol DetailsView: class {
    func setNavigationBarTitle(title: String)

    func goBackToMasterPage()

    func setImageLowResPlaceholder(url: URL)

    func displayErrorMessage(details: String)

    func populateData(data: DetailData)

}
