//
//  DetailsViewController.swift
//  NumbersApplication
//
//  Created by Kamil Buczel on 21.01.2018.
//  Copyright (c) 2018 Kamajabu. All rights reserved.
//
//  This file was generated by the MVP Templates created by Kamil Buczel//

import Foundation
import UIKit
import SDWebImage

class DetailsViewController: UIViewController, DetailsView, ViewWithAlert {
    @IBOutlet weak var detailImage: UIImageView!
    @IBOutlet weak var detailLabel: UILabel!

    var configurator: DetailsConfiguratorImplementation!
    var presenter: DetailsPresenter!

    override func viewDidLoad() {
        super.viewDidLoad()

        guard configurator != nil else {
            goBackToMasterPage()
            return
        }

        configurator.configure(detailsViewController: self)
        presenter.viewDidLoad()
    }

    func setNavigationBarTitle(title: String) {
        self.title = title
    }

    func goBackToMasterPage() {
        navigationController?.navigationController?.popToRootViewController(animated: true)
    }

    func setImageLowResPlaceholder(url: URL) {
        detailImage.sd_setImage(with: url)
    }

    func displayErrorMessage(details: String) {
        AlertModule().displayErrorMessage(details: details,
                                          viewInterface: self,
                                          parentView: self)
    }

    func retryAction() {
        presenter.retryFetch()
    }

    func populateData(data: DetailData) {
        detailLabel.text = data.text

        if let url = URL(string: data.image) {
            detailImage.sd_setImage(with: url)
        }
    }
}
