//
//  MasterConfigurator.swift
//  NumbersApplication
//
//  Created by Kamil Buczel on 21.01.2018.
//  Copyright (c) 2018 Kamajabu. All rights reserved.
//
//  This file was generated by the MVP Templates created by Kamil Buczel//

import Foundation

struct MasterConsts {
    static let masterEndpoint = "http://dev.tapptic.com/test/json.php"
    static let cellHeight: Float = 40

    static let detailSegue = "showDetail"
    static let cellIdentifier = "masterCell"
}

protocol MasterConfigurator {
    func configure(masterViewController: MasterViewController)
}

class MasterConfiguratorImplementation: MasterConfigurator {
    func configure(masterViewController: MasterViewController) {
        let apiGateway = ApiGateway()
        let deserializer = Deserializer()

        masterViewController.presenter = MasterPresenterImplementation(
            view: masterViewController,
            apiGateway: apiGateway,
            deserializer: deserializer)
    }
}
